### ISSUE TITLE
不建议通过这种方式来收集 star

### ISSUE THREAD

**Issue by Mayandev** [zwpro/redCover#1]

**Comment by zwpro** [comment]
> _No description provided._

好的，因为在内测，没问题开源的

**Comment by 1099627357** [comment]
能加一下博主的qq或者微信吗？有些问题请教一下

**Comment by zwpro** [comment]
> _No description provided._
已开源，本条issue


> 能加一下博主的qq或者微信吗？有些问题请教一下

微信：sanxungo

**Comment by zwpro** [comment]
> _No description provided._

已开源唠、
